### PR TITLE
Be extra careful with search terms in meta library

### PR DESCRIPTION
**Pull request by iaman**
A Chansey appears to raise from a bush
Ash exclaims that it's a Chansey, it must be his chance
The Chansey turns out to be Officer Jenny in disguise trying to deter poachers
Can't trust user input.

### CODE REVIEW

**Comment by iaman** [comment]
@joshstoik1 This addresses the two XSS vulnerabilities that were filed on OpenBugBounty for Stern Pinball without anybody addressing them; still in communication with the researcher about the new report but I _suspect_ it will address whatever vulnerability they found.

**Review by joshstoik1 — CHANGES_REQUESTED** [review]
Ah, yup, that's where the XSS slips through on Stern.

But I'm pretty sure those getter methods are actually meant to return unescaped code. The real issue seems to be at the [end of the script](https://github.com/brightbrightgreat/bbg-common/blob/develop/bbg-common/lib/bbg/wp/common/meta.php#L549), where the values are actually printed (for the header/meta context).

I'd recommend implementing the fix there instead. Rewriting those loops as follows would do the trick (and cover all fields, not just the description-during-search):
```
// One pass for propertied tags.
foreach ($out as $item) {
	if (isset($item['property'], $item['content'])) {
		\printf(
			'<meta property="%s" content="%s" />' . "\n",
			\esc_attr($item['property']),
			\esc_attr($item['content'])
		);
	}
}

// One pass for named tags.
foreach ($out as $item) {
	if (isset($item['name'], $item['content'])) {
		\printf(
			'<meta name="%s" content="%s" />' . "\n",
			\esc_attr($item['name']),
			\esc_attr($item['content'])
		);
	}
}
```

**Comment by iaman** [comment]
@joshstoik1 I love that suggestion. Will update this in the morning.

**Comment by iaman** [comment]
@joshstoik1 Updated, let me know when you have the time to look over the change!

**Pull request merged**
